can-define.js
test.js

Basic setter

---

can-define.js
test.js

This PR solve the default value and default Value

Default value

---

can-define.js
test.js

Make default values writable

---

can-define.js
list/list-test.js
list/list.js
map/map-test.js
map/map.js
package.json

**WIP** Do NOT merge, need to update references.

Use can-observation

---

can-define.js
define-helpers/define-helpers.js
define-test.js
docs/define.md
docs/types.get.md
docs/types.propDefinition.md
list/list-test.js
list/list.js
map/docs/define-map.md
map/map-test.js
map/map.js

Supports adding expandos in constructor and cleans up .get and .set

---

define-helpers/define-helpers.js
list/list-test.js
list/list.js
list/test.html
map/map.js

Makes expandos work better on DefineList

---

can-define.js
list/list-test.js
test.js

fixes #29 and adds inline lists

adds inline lists

---

list/list.js
test.js

makes .get work on definelist

---

define-helpers/define-helpers.js
list/list-test.js
list/list.js
map/map-test.js
map/map.js

Allow maps to be passed to maps constructor

---

define-helpers/define-helpers.js
list/list.js
map/map-test.js
map/map.js

makes serialize work right 

---

build.js
can-define.js
dist/global/can-define.js
list/list.js
map/map.js

And uses `+standalone` to build the standalone global so no deps are
needed.

Add define/DefineMap/DefineList to the can namespace

---

list/list-test.js
list/list.js

Complete with docs and tests.  It uses Array.prototype.sort on the list itself, so it allows sorting on dynamic define getter props.  🎉

Add can-define/list/list.prototype.sort

---

map/map-test.js
map/map.js

This reverts commit 79f1cc98c10e31676493f8145769b025018b9b37.

Revert "makes DefineMap isMapLike"

---

map/map-test.js
map/map.js

Handle null values when using set({}) form

---

can-define.js
map/map-test.js
map/map.js
map/test.html

regarding #57 
This PR only has some tests that both error out.
Please let me now if my expectation of how `DefineMap.extend()` works is correct.
You **do not have to merge this PR**, but if it can help find the issue great. I will use this branch to try and find a solution myself.

Failing (error) tests for extending DefineMap constructor functions

---

docs/types.get.md

Closes https://github.com/canjs/can-define/issues/59.

Resolve docs

---

can-define.js
define-test.js
docs/TypeConstructor.md
docs/ValueConstructor.md
docs/define.md
docs/serialize.md
docs/type.md
docs/types.get.md
docs/types.propDefinition.md
docs/types.set.md
docs/value.md
list/docs/events.remove.md
list/list-test.js
map/map-test.js
package.json

For #56 and fixes #43.  Also this shifts the docs around a bit.

adds shorthand getter/setters

---

document.js
list/list.js
map/map-test.js
package.json
test.js

Get jshint running

---

.editorconfig
list/list-test.js
list/list.js

@justinbmeyer can you check this if we can add more test use cases

can-define/list inheritable

---

can-define.js
map/map-test.js

For https://github.com/canjs/canjs/issues/2372

Fix error setting compute type value to null or undefined

---

can-define.js
map/map-test.js

Makes it so definitions are on the proto so they can be detected.

---

can-define.js
docs/type.md
docs/types.propDefinition.md
list/docs/define-list.md
list/docs/prototype.wildcard.md
list/docs/prototype.wildcardItems.md
list/docs/static.extend.md
list/list-test.js
list/list.js
map/docs/define-map.md
map/docs/prototype.wildcard.md
map/docs/static.extend.md
map/map.js
package.json

Solves the post part of issue #14 
Pre-processor still needs to be completed.

14 added and removed

---

define-test.js
map/map-test.js

Closes https://github.com/canjs/can-define/issues/89.

skipping tests in production mode

---

list/list-test.js
list/list.js

Closes https://github.com/canjs/can-define/issues/95.

Handling concatenating lists with `#` property

---

package.json

Part of https://github.com/canjs/canjs/issues/2747.

updating versions

---

can-define.js
map/map-test.js
package.json

Minor performance improvement and fixes extension

---

test/test.js

Fixes issues in https://github.com/canjs/canjs/pull/2916

Update can-define tests to use types.DefineMap

---

map/docs/static.seal.md
map/map-test.js

Write tests and document extending sealed objects

---

map/map.js
test/test.js

Fixes and tests using attr during merge

---

map/map-test.js
test/test.html

Closes https://github.com/canjs/can-define/issues/133.

Handling silent failures for sealed objects in IE9

---

list/list-test.js
list/list.js

Makes it so live-binding can properly respond to a sorted list and are not cloned.

---

list/docs/prototype.wildcard.md

Fix a link in the wildcard docs

---

.travis.yml
list/list.js
map/map.js

closes https://github.com/canjs/can-define/issues/159.

Console logs

---

can-define.js
map/map-test.js

Fixed #162 with the following:
* 'Observation.add' is not called while this.__inSetup is true
* 'getCurrent' is not called while this.__inStetup is true
* Initial value is wrapped in Observation.ignore

#162 .value functions should not be observable.

---

list/list.js

- small documentation fix on filter

---

can-define.js
define-test.js

Defined properties should be configurable

---

map/docs/define-map.md

Fixed DefineMap async example

---

can-define.js

Imports the file instead of the modlet folder.

More specific import

---

test/test.js

Fixes incorrect usage of QUnit.ok as mentioned in canjs/canjs#3276
Closes #211

Fixing the incorrect use of QUnit.ok

---

list/list-test.js
list/list.js
map/map-test.js
map/map.js

closes https://github.com/canjs/can-define/issues/213.

making sure DefineMap and DefineList are observableLike in all browsers

---

map/map-test.js
package.json

fixes Type:DefineMap detection by upgrading can-reflect

---

map/map-test.js

Safari changed their error message for when modifying a sealed object.

fix extensible error message check for new safari

---

benchmark/benchmark.html
benchmark/benchmark.js
can-define.js
define-helpers/define-helpers.js
list/list.js
map/map-test.js
map/map.js
package.json

exposes get/set key value methods

---

package.json

chore(package): update steal-tools to version 1.4.0

---

list/docs/define-list.md
list/list-test.js
list/list.js

Dispatch event when an indexed list value changes.

---

can-define.js
define-test.js
map/map-test.js

Warns when value property is assigned an object.

---

can-define.js
map/map-test.js

Update to give warning if value is set to a constructor

---

can-define.js
map/map-test.js

Fix for https://github.com/canjs/canjs/issues/3541.

Fixing issue with Observation bound to getters that use lastSetVal

---

.gitignore
.npmrc
can-define.js
package.json

closes https://github.com/canjs/can-define/issues/262.

Using can-simple-observable for getters using lastSetValue

---

can-define.js
package.json

Part of https://github.com/canjs/can-define/issues/260.

using can-define-lazy-value

---

docs/define.md
list/docs/define-list.md
map/docs/define-map.md

This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/chasenlehara/e754bc6b6e8cdda69814372a33dfac80**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.

Update docs with new @parent & @collection

---

can-define.js
list/list.js
map/map.js

Use ObservationRecorder.add/ignore

---

package.json

Add can-cid as a dependency

---

map/map-test.js
map/map.js

closes https://github.com/canjs/can-define/issues/303.

adding hasOwnKey and hasKey symbols

---

can-define.js
docs/TypeConstructor.md
docs/default.md
docs/defaultConstructor.md
docs/types.get.md
docs/types.propDefinition.md
docs/types.set.md
docs/value.md
docs/valueOptions.md
list/list-test.js
list/list.js
map/docs/define-map.md
map/docs/static.extend.md
map/map-test.js
package.json
test/test-define-only.js
test/test-list-and-map.js
test/test-value-resolve.js
test/test.js

Value behavior

---

docs/define.md
docs/types.get.md
docs/types.set.md
list/docs/define-list.md
list/docs/events.add.md
list/docs/events.remove.md
map/docs/define-map.md

Fix can-event-queue links

---

benchmark/benchmark.js
build.js
define-helpers/define-helpers.js
ensure-meta.js
list/list.js

This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/Aosanders/245a21b2685ea9e063090206d59386eb**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.

Adds use strict. Fixes canjs/canjs#4217

---

can-define.js
docs/define.md
docs/define.types.md
docs/types.propDefinition.md
test/test-define-only.js

some doc changes and fixes onKeyValue

---

define-helpers/define-helpers.js
map/map-test.js

able to delete a key

---

can-define.js
test/test-list-and-map.js

Closes https://github.com/canjs/can-define/issues/400

Update dispatch to fire `add` on newly add props

---

can-define.js
map/map-test.js

Make sure getSchema works for various type definitions.

---

can-define.js
map/map-test.js

set new prop to undefined dispatch onPatches

---

list/docs/prototype.includes.md
list/list-test.js
list/list.js

Resolves https://github.com/canjs/can-define/issues/277

Fixes #277. Adds 'includes' method to DefineList

---

docs/types.propDefinition.md

Fix docs `SETTER` first example at the line 6 should use `newVal` as argument

fix SETTER code example

---

map/docs/prototype.assign.md

Clarify the assign() docs

---

map/docs/prototype.update.md

Clarify the update() docs

---

list/list-test.js
list/list.js
package.json

[3.x] Use the single reference for turning off both index and key listeners

---

list/list-test.js
map/map-test.js
package.json
test/test-define-only.js
test/test-list-and-map.js
test/test-value-resolve.js
test/test.js

This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/cherifGsoul/e82fd3546da2c3bdabe4b4b9c918d361**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.

Landscaper: QUnit2 upgrade

---

list/list-test.js
list/list.js

Redux of #456 but corrected for some things I overlooked the first time.

[3.x] Fix single reference cases for key and index listeners in DefineList

---

can-define.js
test/test-define-only.js

Trying to set a getter that doesn't take `lastSet` throws an unhelpful error

---

test/test-define-only.js

[Issue #461](https://github.com/canjs/can-define/issues/461)

ie11 more regex fixes
