canjs/can-define

- list/list-test.js
- list/list.js
`.map()` was broken due to missing variable `Define`.  I added tests, which also assure list is of the same constructor.  
I also explicitly tested `replace` since it doesn’t seem to be done already.
> Fix & test List.map()

- list/list-test.js
- map/map-test.js
- map/map.js
Before this, if you called `.get("propName")`, all the getter / setters would be added to that project. 
This caused problems if stache tried to `.get("not")` or some other helper that shouldn't exist because it might add a property to a sealed object.  
This change makes it so 
- if the property is `in` the map, its value is returned.
- if the object is sealed, the undefined value is returned (because no future observable properties can be added, so there's no reason to call `Observation.add`)
- otherwise, setup `Observation.add` in case there is a future property.
> makes it so .get doesn't create properties, only sets up an observable

- can-define.js
- define-test.js
- map/map-test.js
- package.json
This implements iterators for maps and other defined constructors so
that you can do:
```js
for(var [key, value] of map) {
}
```
In supporting browsers and:
```js
var each = require("can-util/js/each/each");
each(map, function(value, key){
});
```
In older browsers. This is a needed feature to make `{{#each map}}` work
in stache.
Closes #54
> Implements iterators for maps.

- package.json
The current npm description describes this library in terms of can.Map, which isn't very useful for new-comers.  The npm description is more likely to be useful to a new dev than a seasoned canner.  :)
> Proposal for a better npm description

- .gitignore
- list/list-test.js
- list/list.js
Closes #60 
Makes concat behave as expected and reference objects passed as args so that `sourceList[ 0 ] === ( sourceList.concat( [] ) )[ 0 ];`.
> 60 fix for concat

- can-define.js
- define-test.js
- docs/TypeConstructor.md
- docs/define.types.md
- list/list.js
Major changes in this PR:
* if `{type: "boolean"}`, `null` and `undefined` remain as is instead of being converted to false.  This makes the "boolean" type align with how numbers, strings, dates are treated.  However, `{type: "htmlbool"}` has not changed and will convert nullish values to `false`.
* Any `Type` conversion will treat `null` and `undefined` as is instead of creating a new instance.
> Consistency of behaviors for passing null and undefined to type and Type

- list/list-test.js
- list/list.js
- map/map-test.js
- map/map.js
Adds can-event methods onto the Map and List Constructors.
```js
var List = DefineList.extend({});
assert.ok(List.on, 'List has event methods.');
```
> Mix events into Map and List Constructors

- package.json
This will prevent Travis from failing during releases because jshint hint has been linting the `./dist` folder.
> Make JsHint ignore the ./dist directory

- can-define.js
- define-test.js
fixes #87.
I'm not in love with this solution.  This makes `defaultValue` know about `set`.  It doesn't work with `async` setters, though it does check to make sure that side-effect only setters aren't run.  
A better solution would somehow be able to run the compiled `setter`, but without having it trigger events or actually do the setting.  
We need sort of a "figure out set value" -> "actually set value" flow.
> Call `set` behavior in `value` or `Value`

- can-define.js
- define-test.js
fixes #132
This manages to use `make.set.setter(` so we don't have to duplicate the behavior of how `set` is called while still not firing an event in the case that `set` returns a value or calls `resolve` immediately.
It does this in a less-than-ideal way performance-wise as it calls `make.set.setter` everytime to generate a function.  This is so we can know the state if the `setter` callback was called immediately.
In the end, this works and is relatively maintainable, while it suffers a bit from a performance drag.
> Make async sets work with `value`

- .travis.yml
- can-define.js
- define-test.js
This fixes the issue with calling `this.val` in a setter where `value` or `Value` of `val` is defined causing infinite recursion.
Closes #142
> Default value setter infinite loop

- list/list-test.js
- list/list.js
DefineList::replace uses can-util/diff to optimize changes (rather than dumping and reinserting everything, as before). Resolves canjs/can-view-live#10
The tests feel a bit off, as it is essentially testing the result of the diff, rather than that can-util/diff was used. It does test that it's not a blanket replace, however.
> DefineList::replace use can-util/diff

- list/list-test.js
- list/list.js
Fixes #153 by return a plain DefineList on `.map()` calls.
> fix map return type (#153)

- can-define.js
- define-helpers/define-helpers.js
- map/map-test.js
- map/map.js
- package.json
Covers #92 and other issues found when trying to convert between can.Map and DefineMap, which aren't currently playing nice with each other in certain cases.
These operations will help bridge that gap, and prevent some issues, but there are limitations to the current approach:
* I haven't touched on anything specific to DefineList yet, and I'm sure it has its own problems, but currently I'm having more, and more frequent, issues going between can.Map and DefineMap.
But here's what's been done so far:
* For cases where DefineMaps are being sent to other objects for assignment, the `constructor` property, the `"*"` defintition, and the prototype functions are made non-enumerable.  This prevents the prototype functions on target objects being overwritten, causing incorrect object behavior, …
> Improve assignment to/from DefineMaps by avoiding copying special keys.

- list/list-test.js
- list/list.js
Updates can-define/list to have a length setter which actually mutates the information stored. If the set length > the current length, the extra values are set to undefined with `.push` (much like when `set`ting a position greater than the current length). If the set length < the current length, extra values are removed via `.splice`.
One issue that I ran into is that the native `splice`, `push`, `pop`, `shift`, and `unshift` each will trigger the length setter. My first solution (see first commit) implemented the functionality of these calls manually, but I realized it wouldn't fire events correctly. I switched to using the already existing `push`/`splice`, but since there is no way to tell the difference between the length setter being called directly vs via one of those methods, I had …
> length setter

- package.json
Explicitly upgrading to can-util > 3.4.0 to try to resolve https://github.com/canjs/can-define/issues/182.
> chore(package): update can-util to version 3.5.1

- can-define.js
- map/map-test.js
Avoids breakage when the value has a replaceWith getter (which itself gets replaced with a `value` property definition on first get of the property)
fixes #182
> Get values before setting them in setup

- can-define.js
If a "replaceWith" property is set, it will just update the definition.  Frr #185 related to #182
> Add setter to replaceWith

- list/list-test.js
Fixes https://github.com/canjs/can-define/issues/191
> Updating list-test.js to not use QUnit.throws

- list/list-test.js
Closes https://github.com/canjs/can-define/issues/191.
> making list-test less restrictive

- list/list-test.js
- list/list.js
Covers all functions explicitly listed in https://github.com/canjs/can-define/issues/81
Tests and documentation included.
> Add all missing ES5 Array prototype functions to DefineList

- can-define.js
Fixes #196  - 'htmlbool' type is never false when set to a "false" or "0"
> Fixes #196 - htmlbool is now false when 'false' or '0'

- list/docs/events.length.md
- list/list-test.js
- list/list.js
Fixes the triggering of `length` events to only trigger when the length changes (#150), and only once (#152). Previously, a change or replace (as opposed to an addition or removal) would trigger 2 changes, as it was treated as an add and a remove, both of which triggered `length`. A simple change (`[1, 2, 3] => [1, 4, 3]`) now produces no `length`, and a replace only produces one if the new length is different. A single push/pop/shift/unshift still only produces 1 event.
Previously, reverse produced 2 events (as it is just a replace), but [there was a test](https://github.com/canjs/can-define/blob/master/list/list-test.js#L178) which verified the existence of both events. That test references issues #851 which does not exist (was this perhaps originally in a different repo?). I have …
> standardize length event triggering

- can-define.js
- list/list-test.js
- map/map-test.js
This issue primarily affects trying to do new data definitions on an unsealed DefineMap after instantiation.  It's an uncommon use case, but it's supported in defined regular objects and should also be supported in DefineMaps if they're not otherwise sealed.
Previously breaking example from #83:
```javascript
var Bar = DefineMap.extend({seal: false}, {
baz: { value : "thud" }
});
var baz = new Bar();
define(baz, {
quux: { value: "jeek" }
}, baz._define);
```
> Don't attempt to redefine _data or _computed on DefineMaps if they're already defined

- define-helpers/define-helpers.js
- map/map-test.js
This replaces the hasMethod function which could return false positives,
and did so with the case of Node.js request objects, with using
can-reflect to determine if an object is observable.
Closes #216
> Replace duck-typing hasMethod with can-reflect

- map/map-test.js
closes https://github.com/canjs/can-define/issues/218.
> skipping Object.seal test in production

- can-define.js
- define-test.js
- test/test.js
See https://github.com/canjs/can-util/issues/225. We are now using `Array.isArray` directly.
> Replace deprecated can-util/js/is-array with Array.isArray

- list/list-test.js
- list/list.js
Removed duplicate assign of `onKeyValue` and `offKeyValue` as well as set a translation handler for `NaN` keys to follow the `can-reflect` event api.
For #252
> Removed redundant setting of keyValue functions

- can-define.js
- define-test.js
- package.json
Closes #149 
Note: the `this.__inSetup` check is included only to align with the `make.get.data` version.
Also closes #246.
> Observe on the object property

- can-define.js
- define-test.js
Tests were inconsistently failing for `can-connect` when all tests for CanJS were ran.
The breaking changes were introduced with this fix: https://github.com/canjs/can-define/pull/244
Discussion of the issue is here: https://github.com/canjs/can-define/issues/149
For: https://github.com/canjs/can-define/issues/149
> Rolling back changes to fix failing can-connect tests

- can-define.js
- define-test.js
In these cases, it's likely that a user meant to use a `Type` def rather than `type`; this uses `can-reflect.isConstructorLike` to determine if the supplied function or object is a constructor.
Fixes #205
> Warn when a constructor is supplied as a type definition

- can-define.js
- define-test.js
If a property has a definition consisting of a zero arg getter and no setter, and the environment is not production, and the user attempts to set the property, this PR generates a warning.
Fixes #202
> Warn when setting a property that has only a zero-arg getter.

- .jshintrc
- ensure-meta.js
- list/list-test.js
- list/list.js
- map/map-test.js
- map/map.js
- package.json
The `DefineMap` log output is the same as the one in `SimpleMap`, `DefineList` has a small variation though:
a) `propertyName` and `length` events use the labels `key`, `is`, and `was`
b) `add` and `remove` use the labels `how`, `what` and `index`.
> Add `.log` to log DefineMap and DefineList changes

- can-define.js
- define-test.js
- docs/types.propDefinition.md
- list/list.js
- map/map-test.js
- map/map.js
- package.json
We want to show an error in development anytime someone tries to use shorthand syntax for a `DefineMap` prop and furthermore, don't assign it.
For instance if someone does:
```js
var ViewModel = DefineMap.extend({
someProp: 'this is some random string and not a type',
someOtherProp: function() {} // <- This is not a Constructor function
});
```
We should ignore both of these cases and throw the error.
The only values allowed with the shorthand can be found here: https://canjs.com/doc/can-define.types.propDefinition.html
Closes https://github.com/canjs/can-define/issues/278
> Don't allow improper shorthand props on DefineMaps and throw error

- can-define.js
- test/test-value-resolve.js
closes https://github.com/canjs/can-define/issues/318.
> preventing events from being dispatched when setting a property that uses resolver

- docs/TypeConstructor.md
- docs/default.md
- docs/defaultConstructor.md
- docs/define.md
- docs/define.types.md
- docs/serialize.md
- docs/type.md
- docs/types.get.md
- docs/types.propDefinition.md
- docs/types.set.md
- docs/value.md
- docs/valueOptions.md
- list/docs/define-list.md
- list/docs/prototype.wildcard.md
- list/docs/prototype.wildcardItems.md
- list/docs/static.extend.md
- map/docs/define-map.md
- map/docs/prototype.forEach.md
- map/docs/static.extend.md
- map/docs/static.seal.md
This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/christopherjbaker/49b7e985b37032902d68a17dd2daa070**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.
> Cleanup markdown sample code

- can-define.js
- list/list-test.js
- list/list.js
- map/map-test.js
- map/map.js
This gives can-define the ability to expose a schema that can-query-logic can understand
> exposes a schema

- map/map.js
People often think that all signatures of`.set` are deprecated. Here is what the deprecation warning looks like now:
> Updating deprecation warning for .set to be more clear

- can-define.js
- map/map-test.js
This fixes warning messages for default values to use 'default/Default' keywords instead of 'value/Value'
> fix warning messages for default values

- can-define.js
- map/map-test.js
Makes this work with types that implement `canSymbol.for("can.new")`.
> Normalize val: Type, val: { Type: Type } and val: { type: Type }

- map/map-test.js
- map/map.js
When a DefineMap doesn't have any computed properties, currently it is
throwing. This fixes it.
> Make canReflect.getOwnKeys work on basic maps

- can-define.js
- map/map-test.js
can-define/map/map-test.js was throwing an error when testing assignment of special keys to a DefineMap object. Added check to see if property being assigned is writable; if not, the property is skipped.
Should we add a warning if someone attempts to add a special key to a DefineMap object?
> Fixes #353. Can-define special-keys assignment does not throw an error

- can-define.js
- map/map-test.js
- test/test-define-only.js
fixes #340 
uses `canReflect.getName()` to get the constructor name.
Had to pass down the `typePrototype` so functions providing warnings could get the name.
> Makes warnings show the constructor type name along with the property name

- map/map.js
Fixes #322 set deprecation warning
This literally cut and pastes the deprecation warning HTML and switches the order of the signatures to start with the non-deprecated signature.  The deprecated signature should be removed in the next major update.
> moved set deprecation warning

- docs/TypeConstructor.md
- docs/identity.md
- docs/serialize.md
- docs/type.md
- docs/types.set.md
- docs/value.md
This is a documentation update fixing many of the issues from #362 
> Type is called before type and before set.
change to:
> The Type constructor is called before the type property...
> 362 fixing documentaiton

- list/list-test.js
- list/list.js
This fixes an issue where lists, when serialized, were not observable.
Meaning adding or removing items from the list did not result in a
`length` event (changing the observation listening).
Fixes #372
> Make serialized lists observable

- docs/default.md
- docs/defaultConstructor.md
- docs/type.md
- docs/types.get.md
- docs/types.propDefinition.md
- docs/types.set.md
- docs/value.md
Continuing to fix #362 
This PR fixes the following issues and continues to update examples across the board.
There's an issue where @codepen doesn't work under @option.
> codepen documentation update

- can-define.js
- define-helpers/define-helpers.js
- map/map-test.js
Fixes #383 
This moves the use of defineExpando to initialization.  This will likely slow up creating a new DefineMap of properties that haven't already been defined.  However, I don't think this is that common of a case.
> uses proper defineExpando in instantiation

- docs/TypeConstructor.md
- docs/default.md
- docs/defaultConstructor.md
- docs/define.md
- docs/define.types.md
- docs/identity.md
- docs/serialize.md
- docs/type.md
- docs/types.get.md
- docs/types.propDefinition.md
- docs/types.set.md
- docs/value.md
This further fixes the following issues in #362.
> Improvements to Can-Define Documentation

- can-define.js
- map/map-test.js
- map/map.js
This makes it possible to define properties after an Observation has
already been created for a serialized DefineMap. See the test for an
example.
> Make serialized DefineMaps observable with late-defined properties

- map/map.js
- package.json
Safari, unlike Chrome, will count shadowed properties in a for/in loop.
Making them non-enumerable as well fixes it. Closes #389
> Fixes enumerability in Safari

- map/map-test.js
- map/map.js
For DefineMaps, this prevents there from being a `_computed` property
that overrides the getter behavior (that sets the _computed on each
instance). This is needed because of #388 which made DefineMap
prototypes observable themselves.
> Prevents _computed from being defined on DefineMap prototypes

- can-define.js
- list/list.js
- map/map-test.js
- map/map.js
- test/test-define-only.js
Set a couple of properties as configurable to prevent IE from freaking out about them.
> Ie11 configurable

- map/map-test.js
- map/map.js
Partially fixes #395 ... if a user calls `DefineMap.prototype.setup` w/i their overwritten setup, it will not seal the map.  However, this can be done by calling `DefineMap.prototype.setup.call(this, props, true)`.
> Make sure to call an overwritten `setup` on the prototype.

- can-define.js
- package.json
- test/test-define-only.js
Addresses https://github.com/canjs/can-define/issues/397. 
Requires the merging of https://github.com/canjs/can-simple-observable/pull/36 before this will pass.
> Fixes #397. Passes default value to Resolver

- list/list-test.js
For #419 
```DefineList.includes``` tests should be ignored in not supported environment (IE11).
In every ```includes``` tests I checked if the ```Array.prototype.includes```  function is present to run the tests otherwise I added ```expect(0)``` (QUnit expects no tests).
> ignore DefineList.includes tests for IE11

- can-define.js
- list/list-test.js
- map/map-test.js
- package.json
Closes https://github.com/canjs/can-define/issues/421.
Depends on https://github.com/canjs/can-define/issues/421 (maybe not?)
> Using the Symbol instead of the __inSetup property

- can-define.js
- map/map-test.js
For  #425
Now `define.expando` convert the value to the custom type if the `defaultDefinition` has `Type` property that has a `Constructor` type in the `*` wildcard type definition.
> Wildcard constructor types should work

- docs/define.md
Just `newVal` instead of `newValue.target.message` in the first example
> Fix first example error

- map/docs/static.extend.md
Change the param to be of `propDefinitions` and include sentence with link to `propDefinitions`
Issue - https://github.com/canjs/can-define/issues/279
> Improve documentation for propDefinitions

- test/test-define-only.js
- test/test.html
Fixed using RegEx for [Issue #461](https://github.com/canjs/can-define/issues/461)
> #461: Tests using canReflect.getName in assertions fail in IE11

- can-define.js
- test/test-define-only.js
This PR fixes two issues - It warns when you have `type` or `Type` with a zero argument `getter` and also fixes `Default` to warn even when the the default value is falsey (currently it only warned when `default` had non-falsey values)
closes #465 
closes #466
> 465 warn for getter with type and 466 default with falsey value

- can-define.js
- test/test-define-only.js
This removes a 'false positive' warning for `type` being ignored with a zero-arg getter.  It now allows the default `type` set by `can-define/map/map` to exist with a zero-arg getter, and not warn. 
Closes #468
> 468  remove false warning if only  default type

- docs/define.md
- list/docs/define-list.md
- map/docs/define-map.md
Moving `can-define` from `can-core` into `can-legacy` for documentation.
Related to https://github.com/canjs/canjs/issues/5170
> change can-core to can-legacy for docs

- can-define.js
- define-helpers/define-helpers.js
- list/list.js
- map/map-test.js
- package.json
For https://github.com/canjs/canjs/issues/4656
Dispatches events with:
```
action: "set",
key: prop,
target: map,
newValue: newVal,
oldValue: oldValue,
```
This enables:
```
map.on("key", ({newValue}) => {})
```
type functions.
> adds newValue and oldValue on event objects
